spring.application.name=edupanel

spring.profiles.active=firebase

# NOTA JOACO: debes crear el proyecto Realtime Database/Auth y dejar
# el archivo de cuenta de servicio en src/main/resources/firebase-config.json.
# Ese archivo esta en .gitignore y no debeS subirlo al repositorio.
firebase.service-account=firebase-config.json
firebase.database-url=https://poocalificaciones-default-rtdb.firebaseio.com
